# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

[licenses]
allow = [
  "Apache-2.0",
  "MIT",

  # Needed for xtask only.
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
  "MPL-2.0",
  "Unicode-3.0",
]


[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "windows-sys", version = "0.52.0" },
]
skip-tree = [
    { name = "getrandom", version = "0.2.15" },
]
