[package]
name = "benchtool"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ext4-view = { path = ".." }
uefi = { version = "0.34.1", features = ["alloc", "global_allocator", "panic_handler"] }
